### ISSUE TITLE
Autosave on actions

### ISSUE THREAD

**Issue by GoffAC** [lbauskar/kanban#1]
Hey man, I really like your work - in the whole of the VScode extensions yours was the simplest to use and most flexible. 

The feature I think you are missing would be autosave. 

I know you have the shortcut, but, for me, this feels more like an embedded app than something I would naturally press `ctrl + s`. As such, a few times now, I have close the tab to keep tidy and found I have lost what I haven't saved! 

I wanted to contribute but I haven't got much head around Typescript yet! Regardless keep it going and great work!

**Comment by lbauskar** [comment]
Thanks for the kind words! Sorry, I haven't updated this in a while. I've been busy with school.

I agree with you that autosaving would be useful. I'm thinking about including a checkbox in the UI for it. Hopefully, it should be included with the next update.

**Comment by lbauskar** [comment]
Alright, I've got an autosave toggle. When active it will save the contents of the kanban board every second.

Ideally, the extension would only autosave once -- right before the window closes; however, the "pagehide" event doesn't work with how I have saving set up. I'll leave this issue open in case I can come up with a way to implement autosave more efficiently within the next week or so.

**Comment by lbauskar** [comment]
I found a better way.
