### ISSUE TITLE
Color palette does not hide when clicking on Hide settings

### ISSUE THREAD

**Issue by vascanera** [lbauskar/kanban#13]
If color palette is open when you click on Hide settings, the palette remains open.

**Comment by md2perpe** [comment]
@lbauskar. Perhaps it's enough to move the color palette `div` element up and include it in the settings `div` element?

I wanted to test to do the above myself, but didn't manage to compile and test the extension from source code.

**Comment by lbauskar** [comment]
Yes, putting the pallete inside the settings div should fix the closing issue. Though you'll probably also have to make some adjustments to the column setting's height for animation purposes.

@md2perpe What's preventing you from compiling the source code?

**Comment by vascanera** [comment]
Happened to me as well. Running npm install crashes the installation, but works ok via yarn.

**Comment by lbauskar** [comment]
Also, I was able to (sorta) fix the pallete closing issue. I just made the column-settings button also close the color pallete. The animation is a bit janky though, so I'll work on it a bit more before pushing it.

**Comment by vascanera** [comment]
I played with the 1.5 branch a bit, indeed, the color palette issue is fixed. Thanks! You can close this issue.

**Comment by md2perpe** [comment]
@lbauskar Running just `yarn` works, but how do I build? I have tried `tsc` and `yarn build`. Both fail.

**Comment by lbauskar** [comment]
`yarn run build` will will run the build scripts. This and other scripts are located in _package.json_ .

**Comment by md2perpe** [comment]
Okay, that worked. But how do I test it? Pressing <kbd>F5</kbd> launches a new instance of VSCode, but the extension seems not to work. I can't find the command "Kanban: View".

**Comment by lbauskar** [comment]
That's... interesting.

The process you described is how I test the extension. I run the build script, then press F5 to launch a new window and test the extension in that window. The window with the test extension should have the title [Extension Development Host] in it.


![image](https://user-images.githubusercontent.com/50561822/154994543-a0be2a05-7e86-43bf-a836-0bf9b5d64f9a.png)

**Comment by md2perpe** [comment]
That window opens, but neither is the command found, nor is there a kanban icon and text in the status bar.

**Comment by md2perpe** [comment]
I found that if I remove `"extensionKind": [ "ui" ],` from package.json then it works. The reason that it doesn't work with this setting is probably because I'm running VSCode from [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux).

**Comment by vascanera** [comment]
I'm on mac, everything works ok, so, it might have something to do with WSL (maybe some dependencies). Also, I removed the (stable) Kanban extension from VSCode before running (npm run build + F5 (debug extension)) the new branch.

**Comment by md2perpe** [comment]
Now I tested outside of WSL and it worked. The commands I ran were `npm i -g yarn`, `yarn` and `yarn run build`, followed by <kbd>F5</kbd> to test and debug the extension. The Kanban icon was shown in the status bar in the test window and the command "Kanban: View" was found.
