### ISSUE TITLE
Project install error via NPM

### ISSUE THREAD

**Issue by vascanera** [lbauskar/kanban#17]
When running `npm install` in the project, the installation fails. It works ok via `yarn`.
<img width="585" alt="image" src="https://user-images.githubusercontent.com/45070144/154585341-b19b2eec-987b-49c1-abd3-4ac17437456c.png">

**Comment by lbauskar** [comment]
I pushed some changes onto the 1.5 branch which fixes that dependency issue. NPM install works on my machine; does it work for you?

**Comment by vascanera** [comment]
Yes. I can confirm, branch 1.5 works with `npm install`. You can close this issue.
