### ISSUE TITLE
Feature request: Save data in workspace

### ISSUE THREAD

**Issue by Alsan** [lbauskar/kanban#2]
Please add option on save data in workspace (I prefer this would be default), so that the kanban can shred with other project members.

**Comment by lbauskar** [comment]
If we're gonna save the state to a file, do you want to be able to name the file yourself or have the extension automatically pick one?
A predefined file would probably be easier to implement (the file would probably be ```.vscode/kanban.json```), but if there's a use-case for custom files I'll go ahead and try that.

Regardless, I'll try to implement something within the next couple days. Thanks for using my extension!

**Comment by lbauskar** [comment]
There's an option to save to a JSON file in 1.3.0
