### ISSUE TITLE
Reload data

### ISSUE THREAD

**Issue by lonix1** [lbauskar/kanban#3]
I wanted to reorder columns, change colors, various things. I thought it may be easiest to edit the json file.

But after that, how do I force the extension to reload that file (other than restarting vscode)?

**Comment by lbauskar** [comment]
Hi Ionix! Thanks for using my extension.

The short answer is that you can reload the file just by closing the tab your board appears in, then opening Kanban again. You don't need to reload the entirety of VS Code.

I was wondering what "various things" you needed to do by editing the JSON. Rearranging columns makes total sense, but you can change a column's color in the GUI. If there's some basic operation you need to use the JSON for please let me know.  Half the point of this extension is to make it easy to update the board.
