### ISSUE TITLE
Change "new taks"-item

### ISSUE THREAD

**Issue by DarkTrick** [lbauskar/kanban#7]
**Currently** it looks like a "create directory" command: 
![image](https://user-images.githubusercontent.com/46980694/136494214-ade298ea-38f0-4ed7-b953-5b40f21cb021.png)

**Suggestion 1** 
change it to something that is clearly not a folder. E.g.
![image](https://user-images.githubusercontent.com/46980694/136494329-b86cd8b1-c007-4166-bc7b-8a8579711cec.png)
![image](https://user-images.githubusercontent.com/46980694/136494337-6c46f2fd-cbd3-4d5b-9b9d-b69d83005e37.png)

**Suggestion 2**
Loose the icon altogether and enable this feature via
 - right click within a column
 - with a "appear-on-hover" button in the top of the column
![image](https://user-images.githubusercontent.com/46980694/136494633-6550fcb6-c543-4ebd-b7ad-753d44374356.png)

**Comment by lbauskar** [comment]
I like your second suggestion and the UI mock-up too! Rather than being completely hidden when not hovered, I think it would be more intuitive if the "Add task"  button/bar was translucent when not hovered. That way a new (or forgetful) user would know it's there.
